version: '3.8'

services:
  app:
    build: .
    ports:
      - "4567:4567"
    depends_on:
      - db
    volumes:
      - gems_volume:/usr/local/bundle
    command: ruby app.rb -o 0.0.0.0

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  gems_volume:
