version: '3.8'

services:
  app:
    build: .
    ports:
      - "4567:4567"
    depends_on:
      - db
    volumes:
      - .:/app
      - gems_volume:/usr/local/bundle
    command: ruby app.rb -o 0.0.0.0
    networks:
      - my_network

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my_network

  db_test:
    image: postgres:latest
    environment:
      POSTGRES_DB: myapp_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

volumes:
  postgres_data:
  gems_volume:

networks:
  my_network:
