version: '3.8'

services:
  app_back: &app_back
    build: .
    ports:
      - "4567:4567"
    depends_on:
      - db
      - redis
    volumes:
      - .:/app
      - gems_volume:/usr/local/bundle
    command: rackup app/back/config.ru -p 4567 -o 0.0.0.0
    environment:
      - REDIS_URL=redis://redis:6379/0

  app_front:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - app_back
    volumes:
      - .:/app
      - gems_volume:/usr/local/bundle
    command: rackup app/front/config.ru -p 3000 -o 0.0.0.0

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  db_test:
    image: postgres
    environment:
      POSTGRES_DB: myapp_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  sidekiq:
    <<: *app_back
    ports: []
    command: sidekiq -r ./app/back/jobs/sidekiq_initializer.rb

  redis:
    image: redis

volumes:
  postgres_data:
  gems_volume:
