development:
  adapter: postgresql
  encoding: unicode
  database: postgres
  username: postgres
  password: postgres
  host: db
  port: 5432

test:
  adapter: postgresql
  encoding: unicode
  database: myapp_test
  username: postgres
  password: postgres
  host: db
  port: 5432
